### ISSUE TITLE
Sign-In Functionality Not Working; Suggest Adding "Sign in with Google" Option

### ISSUE THREAD

**Issue by VanshChitransh** [ypratham/invoice-generator#10]
🐛 Bug Report: Sign-In Functionality Broken

Description:
The sign-in functionality on the website does not work as expected. Clicking on the sign-in button does not log the user in, and there is no response or error message to indicate what went wrong. This issue is affecting both regular sign-ins and third-party authentication methods.

Steps to Reproduce:
Go to the sign-in page of the invoice-generator website.
Enter valid login credentials or try to sign in with Google.
Click the Sign In button.
Observe that nothing happens, and the user is not logged in.

Expected Behavior:
When a user clicks the Sign In button with valid credentials or opts to sign in via Google, they should be authenticated and redirected to the dashboard.

Screenshot:
![Screenshot from 2024-09-27 20-22-36](https://github.com/user-attachments/assets/ddfb9fa8-dd7a-49bd-83d3-b1c48b210f82)

Environment:
Browser: Chrome, Safari, Firefox, etc.
Device: Desktop, Mobile
OS: Windows, macOS, Android, iOS

Additional Notes:
Please look into adding "Sign in with Google" as an additional option to enhance the user experience.

**Comment by VanshChitransh** [comment]
@ypratham I would like to work on this issue in hactoberfest.

**Comment by ypratham** [comment]
@VanshChitransh currently user authentication is far away in the pipeline, I have to setup backend server as well. Right now I am closing this issue. I'll add more issues or you can find other issues or features and I'll assign that you.

User authentication is a coming soon feature.
