### ISSUE TITLE
Add Sticky Navbar to Improve Navigation Experience on Scroll

### ISSUE THREAD

**Issue by VanshChitransh** [ypratham/invoice-generator#11]
🚀 Feature Request: Persistent Navbar on Scroll

Description:
Currently, the navbar disappears as the user scrolls down the page. To improve the user experience, it would be beneficial to have a sticky or fixed navbar that stays visible as the user scrolls. This will make navigation easier and more intuitive, especially on longer pages.

Expected Behavior:
The navbar should remain visible at the top of the page while the user scrolls.
This can be achieved by making the navbar sticky or fixed so that it stays in place even when the user scrolls down.

Benefits:
Easier navigation for users, especially when they need to access the navbar while reading or interacting with content on long pages.
Consistent visibility of key links and sections, improving the overall UX.

Screenshot:
![Screenshot from 2024-09-27 20-24-20](https://github.com/user-attachments/assets/a5ba942e-3fda-412c-9bb0-5524b650af1c)

Environment:
Applies to both desktop and mobile versions of the website.

Additional Notes:
This feature will make the site more user-friendly and improve accessibility by ensuring quick access to navigation elements regardless of scroll position.

**Comment by ypratham** [comment]
@VanshChitransh you may proceed to implement this feature.

**Comment by VanshChitransh** [comment]
@ypratham The issue has been resolved, i will be making my pr tomorrow. 
![Screenshot from 2024-09-30 12-47-14](https://github.com/user-attachments/assets/92d0ede8-9b00-48bd-8f8c-9461bd9c3520)

**Comment by ypratham** [comment]
@VanshChitransh it looks great. Good job, once you raise your PR, I'll review your code and then merge it production branch
