### ISSUE TITLE
 Sign-In Functionality Not Working; Suggest Adding "Sign in with Google" Option

### ISSUE THREAD

**Issue by VanshChitransh** [ypratham/invoice-generator#12]
🐛 Bug Report: Sign-In Functionality Broken

Description:
The sign-in functionality on the website does not work as expected. Clicking on the sign-in button does not log the user in, and there is no response or error message to indicate what went wrong. This issue is affecting both regular sign-ins and third-party authentication methods.

Steps to Reproduce:
Go to the sign-in page of the invoice-generator website.
Enter valid login credentials or try to sign in with Google.
Click the Sign In button.
Observe that nothing happens, and the user is not logged in.

Expected Behavior:
When a user clicks the Sign In button with valid credentials or opts to sign in via Google, they should be authenticated and redirected to the dashboard.

Screenshot:
![Screenshot from 2024-09-27 20-22-36](https://github.com/user-attachments/assets/d6c213bf-a5f1-4527-a4e0-3165ef01b524)

Environment:
Browser: Chrome, Safari, Firefox, etc.
Device: Desktop, Mobile
OS: Windows, macOS, Android, iOS

Additional Notes:
Please look into adding "Sign in with Google" as an additional option to enhance the user experience.

**Comment by VanshChitransh** [comment]
@ypratham I would like to add this Feature.

**Comment by Ncode-93** [comment]
Can add this feature quickly (recently worked on Google OAuth 2.0)

**Comment by ypratham** [comment]
@Ncode-93, after reviewing your profiles, I've decided to assign this issue to @VanshChitransh. Please note that the user sign-in function is not part of our current development plans. We'll be implementing this feature in a future update.

**Comment by VanshChitransh** [comment]
@ypratham Should i work on this issue? or you guy's will be doing it in future?

**Comment by ypratham** [comment]
@VanshChitransh we'll be doing this in near future

**Comment by VanshChitransh** [comment]
@ypratham Please do ping me whenever you guy's will be doing this, thanku.

**Comment by VanshChitransh** [comment]
@ypratham Please close the issue
