### ISSUE TITLE
[Feature Request] Introduce Spotify-Inspired Theme for Invoice Generator

### ISSUE THREAD

**Issue by suryanshsingh2001** [ypratham/invoice-generator#16]
## Description

I aim to enhance the user experience of the invoice generator by adding a Spotify-inspired theme. The new theme will primarily cater to users who prefer viewing invoices as digital soft copies. This theme will feature a dark color scheme with green accents, closely mimicking Spotify's modern, sleek design. The addition of this theme will provide an engaging visual experience while maintaining the invoice's readability and usability.

### Why this is needed:

- **Modern Look**: Most invoices tend to follow a standard, uncolored format. This theme will bring a modern touch, especially for users generating soft copies.
- **User Engagement**: An attractive visual design can improve user experience, making invoices easier and more pleasant to read.
- **Branding Flexibility**: This gives users an option to present their invoices in a way that stands out from traditional formats.

### Key Components:

- **Catchy Visual Design**: A striking dark theme with green accents, inspired by Spotify’s style.
- **Simple and Effective Layout**: Focus on clean typography and easy navigation.
- **Seamless User Experience**: Responsive design across devices and smooth integration with the PDF export function.

### Acceptance Criteria:

- [ ] A Spotify-inspired dark theme with green accents has been successfully implemented.
- [ ] Typography and other UI components (buttons, margins, icons) follow a modern design pattern.
- [ ] The theme is fully responsive and tested across different device sizes.
- [ ] The PDF export functionality preserves the theme without any style-related issues.
- [ ] There are no regressions in existing themes or features.

## Additional Context

This theme primarily targets users who frequently generate soft copy invoices. The design should be visually appealing without compromising on clarity and accessibility.

Feel free to suggest any design changes or improvements during the development process.

![image](https://github.com/user-attachments/assets/26e31057-75bf-40dc-b5d6-0abf17a356c6)

**Comment by ypratham** [comment]
Hey @suryanshsingh2001 this looks good, can you please change the icons to be relevant to invoice rather than the music. Rest all looks good
