### ISSUE TITLE
Add "Download as PDF" button

### ISSUE THREAD

**Issue by ypratham** [ypratham/invoice-generator#4]
Is your feature request related to a problem? Please describe.
Currently, users can create invoices, but there is no option to download the invoice as a PDF. This limits the app's usefulness, as users cannot easily save or share their invoices directly from the application.

Describe the solution you'd like
Implement a "Download as PDF" button on the invoice page that allows users to download the generated invoice as a PDF using [React PDF](https://react-pdf.org/). The PDF should replicate the on-screen invoice, including all relevant details like customer information, invoice items, and totals.

Describe alternatives you've considered

Manually using the browser’s print-to-PDF function, but this often leads to inconsistent formatting and layout issues.
Additional context
React PDF provides a flexible, React-based solution for generating PDFs directly from the application's components. The initial implementation should focus on replicating the current layout with no additional customizations. Future updates can introduce more advanced features.

**Comment by Sauhard74** [comment]
hey @ypratham i would love to contribute to this project as it may seem easy but its a very useful and important feature 
I have worked on web apps and native apps and can help this issue to be resolved

**Comment by ypratham** [comment]
@Sauhard74 you may proceed, I'll assign this issue to you. Make sure to follow all the rules and guidelines. A review will be done before we merge your PR.

**Comment by ovindu-a** [comment]
Hey @ypratham, I would like to work on this too if possible.

**Comment by ypratham** [comment]
@ovindu-a once I get a PR from @Sauhard74 then I'll let you know @ovindu-a on which part u can work if there's anything more we can add

**Comment by Sauhard74** [comment]
hey @ypratham i have fixed the issue and made a pr kindly check it out
