### ISSUE TITLE
Inverted date input fields

### ISSUE THREAD

**Issue by Isax03** [ypratham/invoice-generator#7]
**Describe the bug**  
The invoice generator displays the "Invoice Date" and "Due Date" fields in reverse order. The "Invoice Date" (date of creation) is shown as being after the "Due Date," which is incorrect. Additionally, the "Invoice Date" field allows selecting future dates, while the "Due Date" field restricts the date to the current day (in this sense, the inputs are inverted).

**To Reproduce**  
1. Go to the invoice/receipt generation page.
2. Input the "Invoice Date" and "Due Date."
3. Generate the invoice.
4. Observe that the "Due Date" appears as a date earlier than the "Invoice Date"

**Expected behavior**  
The "Invoice Date" should be the creation date of the invoice, and the "Due Date" should reflect a date after the issue date. The system should ensure that the "Due Date" comes after the "Invoice Date."

**Screenshots**  
Attached is a screenshot of the error:  
![{1301295B-02A2-4E2E-A851-99002C42B7A0}](https://github.com/user-attachments/assets/3ab7361d-4dd3-4376-a8cc-bf44be3a35c1)

**Desktop:**
- OS: Windows 11
- Browser: Brave Browser

**Additional context**  
The "Invoice Date" field allows future dates, while the "Due Date" is restricted to the current day. These input behaviors are inconsistent and should be adjusted.

**Comment by Isax03** [comment]
If you want you can assign it to me. I will work on this after the 1st October 😉

**Comment by ypratham** [comment]
Sure @Isax03, I'll assign this to you add appropriate labels.

**Comment by Isax03** [comment]
@ypratham If you want you can merge my pull request
