### ISSUE TITLE
Implement Dark Mode

### ISSUE THREAD

**Issue by Isax03** [ypratham/invoice-generator#8]
**Feature Request: Dark Mode**  

**Is your feature request related to a problem? Please describe.**  
For users who work late at night or simply prefer a darker interface, the current light-themed interface can cause eye strain and discomfort. A dark mode option would be helpful to reduce eye fatigue in low-light environments.

**Describe the solution you'd like**  
I would like to request the implementation of a dark mode for the invoice/receipt generator. This option would allow users to toggle between the light and dark themes based on their preferences, improving the user experience, especially in dark settings.

**Describe alternatives you've considered**  
Currently, users have to rely on third-party extensions or browser settings to invert colors or reduce brightness, but a built-in dark mode would be a more elegant and accessible solution.

**Additional context**  
Dark mode is becoming a standard feature across modern applications and websites. It offers better usability in low-light environments, enhances focus, and is generally more comfortable for users who prefer it.

**Comment by Isax03** [comment]
I am available to implement that during hacktoberfest

**Comment by ypratham** [comment]
@Isax03 I'll assign this issue to you with appropriate labels.

**Comment by Sauhard74** [comment]
hey i did the download button feature and will be making a pr tomorrow , I wanted to contribute more can I work on this issue? or any other issue?

**Comment by Isax03** [comment]
I want to work on dark mode. If you want you can open another issue if you find a bug/missing feature. However, there is a chance I might not have time to work on it. In that case, I would be happy to hand over the issue to you.

**Comment by ypratham** [comment]
@Sauhard74 you can find new issues, and if @Isax03 don't get time you can contribute to this issue, @Isax03 let me know once

**Comment by Isax03** [comment]
@ypratham You can remove me and add @Sauhard74 , I have no time to work on that

**Comment by ypratham** [comment]
@Isax03 okay, @Sauhard74 are you available to work on this?

**Comment by ahmedrazabaloch** [comment]
@ypratham can you assign it to me

**Comment by ypratham** [comment]
@ahmedrazabaloch sure you can go ahead with this but make sure to create a PR for preview branch

**Comment by ahmedrazabaloch** [comment]
@ypratham PR submitted for dark Mode-Feature

**Comment by ypratham** [comment]
@ahmedrazabaloch please raise a pr for preview branch
