### ISSUE TITLE
Make the Web App Responsive

### ISSUE THREAD

**Issue by priyavratamohan** [ypratham/invoice-generator#9]
**Describe the bug**
On mobile and tablet devices, the form fields and invoice preview overlap, making it difficult to fill in the invoice details or view the preview. The layout isn't responsive, causing elements to stack or display incorrectly on smaller screens.

**To Reproduce**
1. Go to the Web App
2. Change viewport width to that of a Phone and a Tablet
3. Observe the elements overlapping each other.

**Expected behavior**
The form and invoice preview should be displayed in separate, well-organized sections that adjust to different screen sizes. On smaller devices, elements should stack vertically or in a way that prevents overlap, ensuring the form fields remain accessible, and the invoice preview is clearly visible.

**Screenshots**
<img width="376" alt="Screenshot 2024-09-26 at 11 57 22 PM" src="https://github.com/user-attachments/assets/2ff634ba-4c7e-43ab-a56c-cdda2be51e76">
Mobile
<img width="811" alt="Screenshot 2024-09-26 at 11 57 41 PM" src="https://github.com/user-attachments/assets/4401a8ab-2d3c-44fc-97fd-a1616172327f">
Tablet

**Smartphone:**
 - Device: iPhone 11 Pro
 - OS: iOS 14.6
 - Browser : Firefox

**Tablet:**
 - Device: iPad
 - OS: iPadOS 14.7.1
 - Browser : Firefox

**Comment by priyavratamohan** [comment]
I would like to start working on it for Hacktoberfest 2024, could you assign applicable labels for it and assign me this issue?

Thanks a lot!

**Comment by ypratham** [comment]
@priyavratamohan Sure!

**Comment by priyavratamohan** [comment]
Update - 

- Added code to make the Navbar a Hamburger Menu on Mobile Dimensions.
- Made <InvoiceForm /> and <InvoiceWithThemes /> to align vertically in Tablet and Mobile Dimensions.

Need to make more changes, will be done by the weekend.

**Comment by ypratham** [comment]
@priyavratamohan cool
